### ISSUE TITLE
Docs or example projects to get started

### ISSUE THREAD

**Issue by mblode** [flipboxfactory/craft-restful#2]
Hey Nate,
I'm trying to piece together all of your plugins and your Dot All talk to create a REST API for Craft 3 and Craft Commerce 2. Is there any example project that has everything set up or any documentation to get this working? I'm just struggling through the setup process as I'm not too experienced with PHP.
Thanks for your awesome work!

**Comment by nateiler** [comment]
There is a sample project here which might help? https://github.com/flipboxlabs/craft-restful-project
